### ISSUE TITLE
Add Function to Turn Zones on and off

### ISSUE THREAD

**Issue by tanami20** [TimofeyK/cmd4-Daikin-Airbase#3]
Currently, we can turn on and off the A/C, but how can we go about turning the A/C vents on and off for each zone as a function? 

For example, I have a Daikin with 4 zones. On the Daikin app, each zone can be turned on and off. There is only one large A/C machine that runs them all, but you can turn areas on and off as outputs.

**Comment by TimofeyK** [comment]
I am sorry, I did not even see there were open issues :)

My Daikin main controller is a basic one without zones so I cannot help adding support for zones because my would not even accept parameters for zones

You can read this forum thread where API for zones support was discussed and create a separate script for that. Because HomeKit has no concept of airconditioner zones you will need emulate four switches that would turn your zones on and off

https://forums.whirlpool.net.au/archive/2768285
